
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: May  3 2026 15:55:34 EDT (May  3 2026 19:55:34 UTC)

// Verification Directory fv/top 

module ro_netlist(EN, CTRL, NAND_CTRL1, NAND_CTRL2, NAND_CTRL3, CLK);
  input EN, NAND_CTRL1, NAND_CTRL2, NAND_CTRL3;
  input [4:0] CTRL;
  output CLK;
  wire EN, NAND_CTRL1, NAND_CTRL2, NAND_CTRL3;
  wire [4:0] CTRL;
  wire CLK;
endmodule

module top(CLK, EN, RSTN, out_clk);
  input CLK, EN, RSTN;
  output out_clk;
  wire CLK, EN, RSTN;
  wire out_clk;
  wire [4:0] cWord;
  wire [6:0] accum_uut_sum;
  wire dco_out, divide_uut_half_freq, divide_uut_quarter_freq,
       down_out, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire nand1_out, nand2_out, nand3_out, up_out;
  ro_netlist dco_uut(.EN (EN), .CTRL (cWord), .NAND_CTRL1 (nand1_out),
       .NAND_CTRL2 (nand2_out), .NAND_CTRL3 (nand3_out), .CLK
       (dco_out));
  SDFCNQD2BWP16P90 \accum_uut_sum_reg[6] (.CDN (RSTN), .CP (dco_out),
       .D (cWord[4]), .SI (n_43), .SE (n_27), .Q (cWord[4]));
  SDFCNQD2BWP16P90 \accum_uut_sum_reg[5] (.CDN (RSTN), .CP (dco_out),
       .D (cWord[3]), .SI (n_41), .SE (n_27), .Q (cWord[3]));
  XOR3D2BWP16P90 g1334__2398(.A1 (cWord[4]), .A2 (n_16), .A3 (n_42), .Z
       (n_43));
  SDFCNQD2BWP16P90 \accum_uut_sum_reg[4] (.CDN (RSTN), .CP (dco_out),
       .D (cWord[2]), .SI (n_39), .SE (n_27), .Q (cWord[2]));
  OAI211D1BWP16P90 g1336__5107(.A1 (n_18), .A2 (n_38), .B (n_17), .C
       (n_23), .ZN (n_42));
  XNR2D1BWP16P90 g1337__6260(.A1 (n_40), .A2 (n_25), .ZN (n_41));
  SDFCNQD2BWP16P90 \accum_uut_sum_reg[3] (.CDN (RSTN), .CP (dco_out),
       .D (cWord[1]), .SI (n_36), .SE (n_27), .Q (cWord[1]));
  ND2D1BWP16P90 g1339__4319(.A1 (n_38), .A2 (n_17), .ZN (n_40));
  XNR2D1BWP16P90 g1340__8428(.A1 (n_37), .A2 (n_29), .ZN (n_39));
  SDFCNQD2BWP16P90 \accum_uut_sum_reg[2] (.CDN (RSTN), .CP (dco_out),
       .D (cWord[0]), .SI (n_34), .SE (n_27), .Q (cWord[0]));
  IND2D1BWP16P90 g1342__5526(.A1 (n_20), .B1 (n_37), .ZN (n_38));
  SDFCNQD2BWP16P90 \accum_uut_sum_reg[1] (.CDN (RSTN), .CP (dco_out),
       .D (accum_uut_sum[1]), .SI (n_33), .SE (n_27), .Q
       (accum_uut_sum[1]));
  OAI211D1BWP16P90 g1344__6783(.A1 (n_22), .A2 (n_32), .B (n_21), .C
       (n_19), .ZN (n_37));
  XNR2D1BWP16P90 g1345__3680(.A1 (n_35), .A2 (n_30), .ZN (n_36));
  SDFCNQD2BWP16P90 \accum_uut_sum_reg[0] (.CDN (RSTN), .CP (dco_out),
       .D (n_27), .SI (n_26), .SE (accum_uut_sum[0]), .Q
       (accum_uut_sum[0]));
  ND2D1BWP16P90 g1347__1617(.A1 (n_32), .A2 (n_21), .ZN (n_35));
  XNR2D1BWP16P90 g1348__2802(.A1 (n_31), .A2 (n_28), .ZN (n_34));
  XOR3D2BWP16P90 g1349__1705(.A1 (accum_uut_sum[1]), .A2
       (accum_uut_sum[0]), .A3 (n_16), .Z (n_33));
  IND2D1BWP16P90 g1350__5122(.A1 (n_24), .B1 (n_28), .ZN (n_32));
  IND2D1BWP16P90 g1351__8246(.A1 (n_24), .B1 (n_21), .ZN (n_31));
  IND2D1BWP16P90 g1352__7098(.A1 (n_22), .B1 (n_19), .ZN (n_30));
  IND2D1BWP16P90 g1353__6131(.A1 (n_20), .B1 (n_17), .ZN (n_29));
  CKND1BWP16P90 g1354(.I (n_27), .ZN (n_26));
  IND2D1BWP16P90 g1355__1881(.A1 (n_18), .B1 (n_23), .ZN (n_25));
  OAI21D1BWP16P90 g1356__5115(.A1 (n_15), .A2 (n_5), .B (n_9), .ZN
       (n_28));
  OAOI211D1BWP16P90 g1357__7482(.A1 (up_out), .A2 (n_14), .B (n_15), .C
       (n_0), .ZN (n_27));
  NR2D1BWP16P90 g1358__4733(.A1 (n_16), .A2 (cWord[0]), .ZN (n_24));
  ND2D1BWP16P90 g1359__6161(.A1 (n_16), .A2 (cWord[3]), .ZN (n_23));
  NR2D1BWP16P90 g1360__9315(.A1 (n_16), .A2 (cWord[1]), .ZN (n_22));
  ND2D1BWP16P90 g1361__9945(.A1 (n_16), .A2 (cWord[0]), .ZN (n_21));
  NR2D1BWP16P90 g1362__2883(.A1 (n_16), .A2 (cWord[2]), .ZN (n_20));
  ND2D1BWP16P90 g1363__2346(.A1 (n_16), .A2 (cWord[1]), .ZN (n_19));
  NR2D1BWP16P90 g1364__1666(.A1 (n_16), .A2 (cWord[3]), .ZN (n_18));
  ND2D1BWP16P90 g1365__7410(.A1 (n_16), .A2 (cWord[2]), .ZN (n_17));
  CKND1BWP16P90 g1366(.I (n_16), .ZN (n_15));
  INR3D1BWP16P90 g1367__6417(.A1 (up_out), .B1 (down_out), .B2 (n_13),
       .ZN (n_16));
  OAI31D1BWP16P90 g1368__5477(.A1 (n_2), .A2 (n_3), .A3 (n_12), .B
       (down_out), .ZN (n_14));
  INR4D1BWP16P90 g1369__2398(.A1 (n_11), .B1 (cWord[2]), .B2
       (cWord[0]), .B3 (cWord[3]), .ZN (n_13));
  SDFCNQD2BWP16P90 accum_uut_nand1_reg(.CDN (RSTN), .CP (dco_out), .D
       (n_6), .SI (nand1_out), .SE (n_0), .Q (nand1_out));
  IND4D1BWP16P90 g1371__5107(.A1 (n_9), .B1 (cWord[1]), .B2 (cWord[4]),
       .B3 (cWord[3]), .ZN (n_12));
  SDFCNQD2BWP16P90 accum_uut_nand3_reg(.CDN (RSTN), .CP (dco_out), .D
       (n_8), .SI (nand3_out), .SE (n_0), .Q (nand3_out));
  DFCNQD2BWP16P90 pfd_uut_Q_UP_reg(.CDN (n_10), .CP (CLK), .D (n_7), .Q
       (up_out));
  DFCNQD2BWP16P90 pfd_uut_Q_DOWN_reg(.CDN (n_10), .CP (out_clk), .D
       (n_4), .Q (down_out));
  SDFCNQD2BWP16P90 divide_uut_eighth_freq_reg(.CDN (RSTN), .CP
       (divide_uut_quarter_freq), .D (EN), .SI (n_0), .SE (out_clk), .Q
       (out_clk));
  NR3D1BWP16P90 g1376__6260(.A1 (n_6), .A2 (cWord[1]), .A3 (cWord[4]),
       .ZN (n_11));
  SDFCNQD2BWP16P90 accum_uut_nand2_reg(.CDN (RSTN), .CP (dco_out), .D
       (nand2_out), .SI (accum_uut_sum[1]), .SE (EN), .Q (nand2_out));
  SDFCNQD2BWP16P90 divide_uut_half_freq_reg(.CDN (RSTN), .CP (dco_out),
       .D (EN), .SI (n_0), .SE (divide_uut_half_freq), .Q
       (divide_uut_half_freq));
  SDFCNQD2BWP16P90 divide_uut_quarter_freq_reg(.CDN (RSTN), .CP
       (divide_uut_half_freq), .D (EN), .SI (n_0), .SE
       (divide_uut_quarter_freq), .Q (divide_uut_quarter_freq));
  AOI21D1BWP16P90 g1380__4319(.A1 (up_out), .A2 (down_out), .B (n_1),
       .ZN (n_10));
  CKND1BWP16P90 g1381(.I (n_9), .ZN (n_8));
  IND2D1BWP16P90 g1382__8428(.A1 (up_out), .B1 (n_0), .ZN (n_7));
  ND2D1BWP16P90 g1383__5526(.A1 (accum_uut_sum[1]), .A2
       (accum_uut_sum[0]), .ZN (n_9));
  CKND1BWP16P90 g1384(.I (n_5), .ZN (n_6));
  OR2D1BWP16P90 g1385__6783(.A1 (EN), .A2 (down_out), .Z (n_4));
  NR2D1BWP16P90 g1386__3680(.A1 (accum_uut_sum[1]), .A2
       (accum_uut_sum[0]), .ZN (n_5));
  CKND1BWP16P90 g1387(.I (cWord[2]), .ZN (n_3));
  CKND1BWP16P90 g1388(.I (cWord[0]), .ZN (n_2));
  CKND1BWP16P90 g1389(.I (RSTN), .ZN (n_1));
  CKND1BWP16P90 g1390(.I (EN), .ZN (n_0));
endmodule

