
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: May  3 2026 15:24:26 EDT (May  3 2026 19:24:26 UTC)

// Verification Directory fv/top 

module ro_netlist(EN, CTRL, NAND_CTRL1, NAND_CTRL2, NAND_CTRL3, CLK);
  input EN, NAND_CTRL1, NAND_CTRL2, NAND_CTRL3;
  input [3:0] CTRL;
  output CLK;
  wire EN, NAND_CTRL1, NAND_CTRL2, NAND_CTRL3;
  wire [3:0] CTRL;
  wire CLK;
endmodule

module top(CLK, EN, RSTN, out_clk);
  input CLK, EN, RSTN;
  output out_clk;
  wire CLK, EN, RSTN;
  wire out_clk;
  wire [3:0] cWord;
  wire [5:0] accum_uut_sum;
  wire dco_out, divide_uut_half_freq, divide_uut_quarter_freq,
       down_out, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, nand1_out;
  wire nand2_out, nand3_out, up_out;
  ro_netlist dco_uut(.EN (EN), .CTRL (cWord), .NAND_CTRL1 (nand1_out),
       .NAND_CTRL2 (nand2_out), .NAND_CTRL3 (nand3_out), .CLK
       (dco_out));
  SDFCNQD2BWP16P90 \accum_uut_sum_reg[5] (.CDN (RSTN), .CP (dco_out),
       .D (cWord[3]), .SI (n_34), .SE (n_22), .Q (cWord[3]));
  SDFCNQD2BWP16P90 \accum_uut_sum_reg[4] (.CDN (RSTN), .CP (dco_out),
       .D (cWord[2]), .SI (n_33), .SE (n_22), .Q (cWord[2]));
  XOR3D2BWP16P90 g1091__2398(.A1 (cWord[3]), .A2 (n_16), .A3 (n_32), .Z
       (n_34));
  FA1D1BWP16P90 g1092__5107(.A (n_16), .B (cWord[2]), .CI (n_31), .CO
       (n_32), .S (n_33));
  SDFCNQD2BWP16P90 \accum_uut_sum_reg[3] (.CDN (RSTN), .CP (dco_out),
       .D (cWord[1]), .SI (n_30), .SE (n_22), .Q (cWord[1]));
  SDFCNQD2BWP16P90 \accum_uut_sum_reg[2] (.CDN (RSTN), .CP (dco_out),
       .D (cWord[0]), .SI (n_28), .SE (n_22), .Q (cWord[0]));
  SDFCNQD2BWP16P90 \accum_uut_sum_reg[1] (.CDN (RSTN), .CP (dco_out),
       .D (accum_uut_sum[1]), .SI (n_27), .SE (n_22), .Q
       (accum_uut_sum[1]));
  OAI211D1BWP16P90 g1096__6260(.A1 (n_18), .A2 (n_26), .B (n_19), .C
       (n_17), .ZN (n_31));
  XNR2D1BWP16P90 g1097__4319(.A1 (n_29), .A2 (n_24), .ZN (n_30));
  SDFCNQD2BWP16P90 \accum_uut_sum_reg[0] (.CDN (RSTN), .CP (dco_out),
       .D (n_22), .SI (n_21), .SE (accum_uut_sum[0]), .Q
       (accum_uut_sum[0]));
  ND2D1BWP16P90 g1099__8428(.A1 (n_26), .A2 (n_19), .ZN (n_29));
  XNR2D1BWP16P90 g1100__5526(.A1 (n_25), .A2 (n_23), .ZN (n_28));
  XOR3D2BWP16P90 g1101__6783(.A1 (accum_uut_sum[1]), .A2
       (accum_uut_sum[0]), .A3 (n_16), .Z (n_27));
  IND2D1BWP16P90 g1102__3680(.A1 (n_20), .B1 (n_23), .ZN (n_26));
  IND2D1BWP16P90 g1103__1617(.A1 (n_20), .B1 (n_19), .ZN (n_25));
  IND2D1BWP16P90 g1104__2802(.A1 (n_18), .B1 (n_17), .ZN (n_24));
  CKND1BWP16P90 g1105(.I (n_22), .ZN (n_21));
  OAI21D1BWP16P90 g1106__1705(.A1 (n_15), .A2 (n_8), .B (n_6), .ZN
       (n_23));
  OAOI211D1BWP16P90 g1107__5122(.A1 (up_out), .A2 (n_14), .B (n_15), .C
       (n_3), .ZN (n_22));
  NR2D1BWP16P90 g1108__8246(.A1 (n_16), .A2 (cWord[0]), .ZN (n_20));
  ND2D1BWP16P90 g1109__7098(.A1 (n_16), .A2 (cWord[0]), .ZN (n_19));
  NR2D1BWP16P90 g1110__6131(.A1 (n_16), .A2 (cWord[1]), .ZN (n_18));
  ND2D1BWP16P90 g1111__1881(.A1 (n_16), .A2 (cWord[1]), .ZN (n_17));
  CKND1BWP16P90 g1112(.I (n_16), .ZN (n_15));
  INR3D1BWP16P90 g1113__5115(.A1 (up_out), .B1 (down_out), .B2 (n_13),
       .ZN (n_16));
  IOA21D1BWP16P90 g1114__7482(.A1 (n_12), .A2 (cWord[2]), .B
       (down_out), .ZN (n_14));
  NR4D1BWP16P90 g1115__4733(.A1 (n_11), .A2 (cWord[1]), .A3 (cWord[2]),
       .A4 (cWord[0]), .ZN (n_13));
  SDFCNQD2BWP16P90 accum_uut_nand1_reg(.CDN (RSTN), .CP (dco_out), .D
       (n_9), .SI (nand1_out), .SE (n_3), .Q (nand1_out));
  INR4D1BWP16P90 g1117__6161(.A1 (cWord[3]), .B1 (n_2), .B2 (n_1), .B3
       (n_6), .ZN (n_12));
  SDFCNQD2BWP16P90 accum_uut_nand3_reg(.CDN (RSTN), .CP (dco_out), .D
       (n_5), .SI (nand3_out), .SE (n_3), .Q (nand3_out));
  SDFCNQD2BWP16P90 divide_uut_half_freq_reg(.CDN (RSTN), .CP (dco_out),
       .D (EN), .SI (n_3), .SE (divide_uut_half_freq), .Q
       (divide_uut_half_freq));
  DFCNQD2BWP16P90 pfd_uut_Q_DOWN_reg(.CDN (n_10), .CP (out_clk), .D
       (n_4), .Q (down_out));
  DFCNQD2BWP16P90 pfd_uut_Q_UP_reg(.CDN (n_10), .CP (CLK), .D (n_7), .Q
       (up_out));
  SDFCNQD2BWP16P90 accum_uut_nand2_reg(.CDN (RSTN), .CP (dco_out), .D
       (nand2_out), .SI (accum_uut_sum[1]), .SE (EN), .Q (nand2_out));
  SDFCNQD2BWP16P90 divide_uut_quarter_freq_reg(.CDN (RSTN), .CP
       (divide_uut_half_freq), .D (EN), .SI (n_3), .SE
       (divide_uut_quarter_freq), .Q (divide_uut_quarter_freq));
  SDFCNQD2BWP16P90 divide_uut_eighth_freq_reg(.CDN (RSTN), .CP
       (divide_uut_quarter_freq), .D (EN), .SI (n_3), .SE (out_clk), .Q
       (out_clk));
  OR2D1BWP16P90 g1125__9315(.A1 (n_9), .A2 (cWord[3]), .Z (n_11));
  AOI21D1BWP16P90 g1126__9945(.A1 (up_out), .A2 (down_out), .B (n_0),
       .ZN (n_10));
  CKND1BWP16P90 g1127(.I (n_8), .ZN (n_9));
  IND2D1BWP16P90 g1128__2883(.A1 (up_out), .B1 (n_3), .ZN (n_7));
  NR2D1BWP16P90 g1129__2346(.A1 (accum_uut_sum[1]), .A2
       (accum_uut_sum[0]), .ZN (n_8));
  CKND1BWP16P90 g1130(.I (n_6), .ZN (n_5));
  OR2D1BWP16P90 g1131__1666(.A1 (EN), .A2 (down_out), .Z (n_4));
  ND2D1BWP16P90 g1132__7410(.A1 (accum_uut_sum[1]), .A2
       (accum_uut_sum[0]), .ZN (n_6));
  CKND1BWP16P90 g1133(.I (EN), .ZN (n_3));
  CKND1BWP16P90 g1134(.I (cWord[1]), .ZN (n_2));
  CKND1BWP16P90 g1135(.I (cWord[0]), .ZN (n_1));
  CKND1BWP16P90 g1136(.I (RSTN), .ZN (n_0));
endmodule

