
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Apr 30 2026 14:34:20 EDT (Apr 30 2026 18:34:20 UTC)

// Verification Directory fv/ro 

module ro(EN, CLK);
  input EN;
  output CLK;
  wire EN;
  wire CLK;
  wire n_3, node0, node1;
  ND2D4BWP16P90 nand1(.A1 (EN), .A2 (n_3), .ZN (node0));
  INVD2BWP16P90 inv1(.I (node0), .ZN (node1));
  INVD2BWP16P90 inv2(.I (node1), .ZN (CLK));
  CKBD1BWP16P90 cdn_loop_breaker(.I (CLK), .Z (n_3));
endmodule

