
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Apr 30 2026 15:38:26 EDT (Apr 30 2026 19:38:26 UTC)

// Verification Directory fv/ro_netlist 

module ro_netlist(CTRL, NAND_CTRL1, NAND_CTRL2, NAND_CTRL3, CLK);
  input [4:0] CTRL;
  input NAND_CTRL1, NAND_CTRL2, NAND_CTRL3;
  output CLK;
  wire [4:0] CTRL;
  wire NAND_CTRL1, NAND_CTRL2, NAND_CTRL3;
  wire CLK;
  wire UNCONNECTED, delay_out_1, delay_out_2, delay_out_3, delay_out_4,
       delay_out_5, delay_out_6, delay_out_7;
  wire delay_out_8, delay_out_9, delay_out_10, delay_out_11,
       delay_out_12, delay_out_13, delay_out_14, delay_out_15;
  wire delay_out_16, delay_out_17, delay_out_18, mux_1_1out,
       mux_1_2out, mux_1_3out, mux_1_4out, mux_1_5out;
  wire mux_1_6out, mux_2_1out, mux_2_2out, mux_out, n_9, n_10, n_11,
       n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_26, start_inv_out;
  ND4D4BWP16P90 nand_gate_capacitor(.A1 (mux_out), .A2 (NAND_CTRL1),
       .A3 (NAND_CTRL2), .A4 (NAND_CTRL2), .ZN (UNCONNECTED));
  INVD2BWP16P90 start_inv(.I (mux_out), .ZN (start_inv_out));
  CKBD2BWP16P90 delay_element1(.I (start_inv_out), .Z (delay_out_1));
  CKBD2BWP16P90 delay_element2(.I (delay_out_1), .Z (delay_out_2));
  CKBD2BWP16P90 delay_element3(.I (delay_out_2), .Z (delay_out_3));
  CKBD2BWP16P90 delay_element4(.I (delay_out_3), .Z (delay_out_4));
  CKBD2BWP16P90 delay_element5(.I (delay_out_4), .Z (delay_out_5));
  CKBD2BWP16P90 delay_element6(.I (delay_out_5), .Z (delay_out_6));
  CKBD2BWP16P90 delay_element7(.I (delay_out_6), .Z (delay_out_7));
  CKBD2BWP16P90 delay_element8(.I (delay_out_7), .Z (delay_out_8));
  CKBD2BWP16P90 delay_element9(.I (delay_out_8), .Z (delay_out_9));
  CKBD2BWP16P90 delay_element10(.I (delay_out_9), .Z (delay_out_10));
  CKBD2BWP16P90 delay_element11(.I (delay_out_10), .Z (delay_out_11));
  CKBD2BWP16P90 delay_element12(.I (delay_out_11), .Z (delay_out_12));
  CKBD2BWP16P90 delay_element13(.I (delay_out_12), .Z (delay_out_13));
  CKBD2BWP16P90 delay_element14(.I (delay_out_13), .Z (delay_out_14));
  CKBD2BWP16P90 delay_element15(.I (delay_out_14), .Z (delay_out_15));
  CKBD2BWP16P90 delay_element16(.I (delay_out_15), .Z (delay_out_16));
  CKBD2BWP16P90 delay_element17(.I (delay_out_16), .Z (delay_out_17));
  CKBD2BWP16P90 delay_element18(.I (delay_out_17), .Z (delay_out_18));
  MUX3ND4BWP16P90 mux_1_1(.I0 (n_26), .I1 (n_25), .I2 (n_24), .S0
       (CTRL[0]), .S1 (CTRL[1]), .ZN (mux_1_1out));
  MUX3ND4BWP16P90 mux_1_2(.I0 (n_23), .I1 (n_22), .I2 (n_21), .S0
       (CTRL[0]), .S1 (CTRL[1]), .ZN (mux_1_2out));
  MUX3ND4BWP16P90 mux_1_3(.I0 (n_20), .I1 (n_19), .I2 (n_18), .S0
       (CTRL[0]), .S1 (CTRL[1]), .ZN (mux_1_3out));
  MUX3ND4BWP16P90 mux_1_4(.I0 (n_17), .I1 (n_16), .I2 (n_15), .S0
       (CTRL[0]), .S1 (CTRL[1]), .ZN (mux_1_4out));
  MUX3ND4BWP16P90 mux_1_5(.I0 (n_14), .I1 (n_13), .I2 (n_12), .S0
       (CTRL[0]), .S1 (CTRL[1]), .ZN (mux_1_5out));
  MUX3ND4BWP16P90 mux_1_6(.I0 (n_11), .I1 (n_10), .I2 (n_9), .S0
       (CTRL[0]), .S1 (CTRL[1]), .ZN (mux_1_6out));
  MUX3ND4BWP16P90 mux_2_1(.I0 (mux_1_1out), .I1 (mux_1_2out), .I2
       (mux_1_3out), .S0 (CTRL[2]), .S1 (CTRL[3]), .ZN (mux_2_1out));
  MUX3ND4BWP16P90 mux_2_2(.I0 (mux_1_4out), .I1 (mux_1_5out), .I2
       (mux_1_6out), .S0 (CTRL[2]), .S1 (CTRL[3]), .ZN (mux_2_2out));
  MUX2ND4BWP16P90 mux_3(.I0 (mux_2_1out), .I1 (mux_2_2out), .S
       (CTRL[4]), .ZN (mux_out));
  CKBD1BWP16P90 cdn_loop_breaker(.I (delay_out_18), .Z (n_9));
  CKBD1BWP16P90 cdn_loop_breaker1(.I (delay_out_17), .Z (n_10));
  CKBD1BWP16P90 cdn_loop_breaker2(.I (delay_out_16), .Z (n_11));
  CKBD1BWP16P90 cdn_loop_breaker3(.I (delay_out_15), .Z (n_12));
  CKBD1BWP16P90 cdn_loop_breaker4(.I (delay_out_14), .Z (n_13));
  CKBD1BWP16P90 cdn_loop_breaker5(.I (delay_out_13), .Z (n_14));
  CKBD1BWP16P90 cdn_loop_breaker6(.I (delay_out_12), .Z (n_15));
  CKBD1BWP16P90 cdn_loop_breaker7(.I (delay_out_11), .Z (n_16));
  CKBD1BWP16P90 cdn_loop_breaker8(.I (delay_out_10), .Z (n_17));
  CKBD1BWP16P90 cdn_loop_breaker9(.I (delay_out_9), .Z (n_18));
  CKBD1BWP16P90 cdn_loop_breaker10(.I (delay_out_8), .Z (n_19));
  CKBD1BWP16P90 cdn_loop_breaker11(.I (delay_out_7), .Z (n_20));
  CKBD1BWP16P90 cdn_loop_breaker12(.I (delay_out_6), .Z (n_21));
  CKBD1BWP16P90 cdn_loop_breaker13(.I (delay_out_5), .Z (n_22));
  CKBD1BWP16P90 cdn_loop_breaker14(.I (delay_out_4), .Z (n_23));
  CKBD1BWP16P90 cdn_loop_breaker15(.I (delay_out_3), .Z (n_24));
  CKBD1BWP16P90 cdn_loop_breaker16(.I (delay_out_2), .Z (n_25));
  CKBD1BWP16P90 cdn_loop_breaker17(.I (delay_out_1), .Z (n_26));
endmodule

