
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: May  4 2026 14:55:35 EDT (May  4 2026 18:55:35 UTC)

// Verification Directory fv/top 

module top(CLK, EN, RSTN, out_clk);
  input CLK, EN, RSTN;
  output out_clk;
  wire CLK, EN, RSTN;
  wire out_clk;
  wire [4:0] cWord;
  wire [6:0] accum_uut_sum;
  wire dco_out, dco_uut_delay_out_1, dco_uut_n_10, dco_uut_n_11,
       dco_uut_n_12, dco_uut_n_13, dco_uut_n_14, dco_uut_n_15;
  wire dco_uut_n_16, dco_uut_n_17, dco_uut_n_18, dco_uut_n_19,
       dco_uut_n_20, dco_uut_n_21, dco_uut_n_22, dco_uut_n_23;
  wire dco_uut_n_26, dco_uut_n_27, dco_uut_nand_out,
       divide_uut_half_freq, divide_uut_quarter_freq, down_out, n_0,
       n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, up_out;
  CKBD1BWP16P90 dco_uut_cdn_loop_breaker(.I (dco_uut_delay_out_1), .Z
       (dco_uut_n_10));
  CKBD1BWP16P90 dco_uut_cdn_loop_breaker1(.I (dco_uut_delay_out_1), .Z
       (dco_uut_n_11));
  CKBD1BWP16P90 dco_uut_cdn_loop_breaker2(.I (dco_uut_delay_out_1), .Z
       (dco_uut_n_12));
  CKBD1BWP16P90 dco_uut_cdn_loop_breaker3(.I (dco_uut_delay_out_1), .Z
       (dco_uut_n_13));
  CKBD1BWP16P90 dco_uut_cdn_loop_breaker4(.I (dco_uut_delay_out_1), .Z
       (dco_uut_n_14));
  CKBD1BWP16P90 dco_uut_cdn_loop_breaker5(.I (dco_uut_delay_out_1), .Z
       (dco_uut_n_15));
  CKBD1BWP16P90 dco_uut_cdn_loop_breaker6(.I (dco_uut_delay_out_1), .Z
       (dco_uut_n_16));
  CKBD1BWP16P90 dco_uut_cdn_loop_breaker7(.I (dco_uut_delay_out_1), .Z
       (dco_uut_n_17));
  CKBD1BWP16P90 dco_uut_cdn_loop_breaker8(.I (dco_uut_delay_out_1), .Z
       (dco_uut_n_18));
  CKBD1BWP16P90 dco_uut_cdn_loop_breaker9(.I (dco_uut_delay_out_1), .Z
       (dco_uut_n_19));
  CKBD1BWP16P90 dco_uut_cdn_loop_breaker10(.I (dco_uut_delay_out_1), .Z
       (dco_uut_n_20));
  CKBD1BWP16P90 dco_uut_cdn_loop_breaker11(.I (dco_uut_delay_out_1), .Z
       (dco_uut_n_21));
  CKBD1BWP16P90 dco_uut_cdn_loop_breaker12(.I (dco_uut_delay_out_1), .Z
       (dco_uut_n_22));
  CKBD1BWP16P90 dco_uut_cdn_loop_breaker13(.I (dco_uut_delay_out_1), .Z
       (dco_uut_n_23));
  CKBD1BWP16P90 dco_uut_cdn_loop_breaker16(.I (dco_uut_delay_out_1), .Z
       (dco_uut_n_26));
  CKBD1BWP16P90 dco_uut_cdn_loop_breaker17(.I (dco_uut_delay_out_1), .Z
       (dco_uut_n_27));
  CKND1BWP16P90 g538(.I (dco_uut_nand_out), .ZN (dco_uut_delay_out_1));
  ND2D1BWP16P90 g855__2398(.A1 (EN), .A2 (dco_out), .ZN
       (dco_uut_nand_out));
  OAI221D1BWP16P90 g856__5107(.A1 (n_62), .A2 (cWord[4]), .B1
       (cWord[3]), .B2 (n_63), .C (n_64), .ZN (dco_out));
  ND3D1BWP16P90 g857__6260(.A1 (n_61), .A2 (cWord[4]), .A3 (cWord[3]),
       .ZN (n_64));
  AOI21D1BWP16P90 g858__4319(.A1 (n_59), .A2 (cWord[4]), .B (n_60), .ZN
       (n_63));
  IOA21D1BWP16P90 g859__8428(.A1 (n_56), .A2 (n_57), .B (cWord[3]), .ZN
       (n_62));
  IOA21D1BWP16P90 g860__5526(.A1 (n_48), .A2 (dco_uut_n_10), .B (n_58),
       .ZN (n_61));
  AOI21D1BWP16P90 g861__6783(.A1 (n_53), .A2 (n_52), .B (cWord[4]), .ZN
       (n_60));
  ND2D1BWP16P90 g862__3680(.A1 (n_55), .A2 (n_54), .ZN (n_59));
  AOI222D1BWP16P90 g863__1617(.A1 (n_49), .A2 (dco_uut_n_13), .B1
       (n_50), .B2 (dco_uut_n_12), .C1 (n_51), .C2 (dco_uut_n_11), .ZN
       (n_58));
  AOI22D1BWP16P90 g864__2802(.A1 (n_49), .A2 (dco_uut_n_21), .B1
       (n_50), .B2 (dco_uut_n_20), .ZN (n_57));
  AOI22D1BWP16P90 g865__1705(.A1 (n_51), .A2 (dco_uut_n_19), .B1
       (n_48), .B2 (dco_uut_n_18), .ZN (n_56));
  AOI22D1BWP16P90 g866__5122(.A1 (n_50), .A2 (dco_uut_n_16), .B1
       (n_51), .B2 (dco_uut_n_15), .ZN (n_55));
  AOI22D1BWP16P90 g867__8246(.A1 (n_49), .A2 (dco_uut_n_17), .B1
       (n_48), .B2 (dco_uut_n_14), .ZN (n_54));
  AOI22D1BWP16P90 g868__7098(.A1 (n_50), .A2 (dco_uut_n_22), .B1
       (n_51), .B2 (dco_uut_n_27), .ZN (n_53));
  AOI22D1BWP16P90 g869__6131(.A1 (n_49), .A2 (dco_uut_n_23), .B1
       (n_48), .B2 (dco_uut_n_26), .ZN (n_52));
  INR2D1BWP16P90 g870__1881(.A1 (cWord[1]), .B1 (cWord[0]), .ZN (n_51));
  INR2D1BWP16P90 g871__5115(.A1 (cWord[0]), .B1 (cWord[1]), .ZN (n_50));
  NR2D1BWP16P90 g872__7482(.A1 (cWord[1]), .A2 (cWord[0]), .ZN (n_49));
  AN2D1BWP16P90 g873__4733(.A1 (cWord[1]), .A2 (cWord[0]), .Z (n_48));
  DFCNQD2BWP16P90 \accum_uut_sum_reg[6] (.CDN (RSTN), .CP (dco_out), .D
       (n_47), .Q (cWord[4]));
  CKMUX2D1BWP16P90 g998__6161(.I0 (n_45), .I1 (cWord[4]), .S (n_25), .Z
       (n_47));
  DFCNQD2BWP16P90 \accum_uut_sum_reg[5] (.CDN (RSTN), .CP (dco_out), .D
       (n_46), .Q (cWord[3]));
  CKMUX2D1BWP16P90 g1000__9315(.I0 (n_42), .I1 (cWord[3]), .S (n_25),
       .Z (n_46));
  XOR3D2BWP16P90 g1001__9945(.A1 (cWord[4]), .A2 (n_15), .A3 (n_44), .Z
       (n_45));
  DFCNQD2BWP16P90 \accum_uut_sum_reg[4] (.CDN (RSTN), .CP (dco_out), .D
       (n_43), .Q (accum_uut_sum[4]));
  OAI211D1BWP16P90 g1003__2883(.A1 (n_17), .A2 (n_38), .B (n_20), .C
       (n_18), .ZN (n_44));
  CKMUX2D1BWP16P90 g1004__2346(.I0 (n_39), .I1 (accum_uut_sum[4]), .S
       (n_25), .Z (n_43));
  XNR2D1BWP16P90 g1005__1666(.A1 (n_41), .A2 (n_26), .ZN (n_42));
  DFCNQD2BWP16P90 \accum_uut_sum_reg[3] (.CDN (RSTN), .CP (dco_out), .D
       (n_40), .Q (cWord[1]));
  ND2D1BWP16P90 g1007__7410(.A1 (n_38), .A2 (n_20), .ZN (n_41));
  CKMUX2D1BWP16P90 g1008__6417(.I0 (n_34), .I1 (cWord[1]), .S (n_25),
       .Z (n_40));
  XOR2D1BWP16P90 g1009__5477(.A1 (n_37), .A2 (n_27), .Z (n_39));
  DFCNQD2BWP16P90 \accum_uut_sum_reg[1] (.CDN (RSTN), .CP (dco_out), .D
       (n_36), .Q (accum_uut_sum[1]));
  IND2D1BWP16P90 g1011__2398(.A1 (n_23), .B1 (n_37), .ZN (n_38));
  DFCNQD2BWP16P90 \accum_uut_sum_reg[2] (.CDN (RSTN), .CP (dco_out), .D
       (n_35), .Q (cWord[0]));
  CKMUX2D1BWP16P90 g1013__5107(.I0 (n_30), .I1 (accum_uut_sum[1]), .S
       (n_25), .Z (n_36));
  OAI211D1BWP16P90 g1014__6260(.A1 (n_21), .A2 (n_29), .B (n_16), .C
       (n_22), .ZN (n_37));
  CKMUX2D1BWP16P90 g1015__4319(.I0 (n_31), .I1 (cWord[0]), .S (n_25),
       .Z (n_35));
  XNR2D1BWP16P90 g1016__8428(.A1 (n_32), .A2 (n_28), .ZN (n_34));
  DFCNQD2BWP16P90 \accum_uut_sum_reg[0] (.CDN (RSTN), .CP (dco_out), .D
       (n_33), .Q (accum_uut_sum[0]));
  XNR2D1BWP16P90 g1018__5526(.A1 (n_25), .A2 (accum_uut_sum[0]), .ZN
       (n_33));
  ND2D1BWP16P90 g1019__6783(.A1 (n_29), .A2 (n_16), .ZN (n_32));
  XNR2D1BWP16P90 g1020__3680(.A1 (n_24), .A2 (n_1), .ZN (n_31));
  XOR3D2BWP16P90 g1021__1617(.A1 (accum_uut_sum[1]), .A2
       (accum_uut_sum[0]), .A3 (n_15), .Z (n_30));
  IND2D1BWP16P90 g1022__2802(.A1 (n_19), .B1 (n_1), .ZN (n_29));
  IND2D1BWP16P90 g1023__1705(.A1 (n_21), .B1 (n_22), .ZN (n_28));
  INR2D1BWP16P90 g1024__5122(.A1 (n_20), .B1 (n_23), .ZN (n_27));
  IND2D1BWP16P90 g1025__8246(.A1 (n_17), .B1 (n_18), .ZN (n_26));
  IND2D1BWP16P90 g1026__7098(.A1 (n_19), .B1 (n_16), .ZN (n_24));
  OAI21D1BWP16P90 g1028__6131(.A1 (n_15), .A2 (n_14), .B (EN), .ZN
       (n_25));
  NR2D1BWP16P90 g1029__1881(.A1 (n_15), .A2 (accum_uut_sum[4]), .ZN
       (n_23));
  ND2D1BWP16P90 g1030__5115(.A1 (n_15), .A2 (cWord[1]), .ZN (n_22));
  NR2D1BWP16P90 g1031__7482(.A1 (n_15), .A2 (cWord[1]), .ZN (n_21));
  ND2D1BWP16P90 g1032__4733(.A1 (n_15), .A2 (accum_uut_sum[4]), .ZN
       (n_20));
  NR2D1BWP16P90 g1033__6161(.A1 (n_15), .A2 (cWord[0]), .ZN (n_19));
  ND2D1BWP16P90 g1034__9315(.A1 (n_15), .A2 (cWord[3]), .ZN (n_18));
  NR2D1BWP16P90 g1035__9945(.A1 (n_15), .A2 (cWord[3]), .ZN (n_17));
  ND2D1BWP16P90 g1036__2883(.A1 (n_15), .A2 (cWord[0]), .ZN (n_16));
  INR3D1BWP16P90 g1038__2346(.A1 (up_out), .B1 (down_out), .B2 (n_12),
       .ZN (n_15));
  INR3D1BWP16P90 g1039__1666(.A1 (down_out), .B1 (up_out), .B2 (n_13),
       .ZN (n_14));
  AN4D1BWP16P90 g1040__7410(.A1 (n_0), .A2 (cWord[3]), .A3 (cWord[0]),
       .A4 (accum_uut_sum[4]), .Z (n_13));
  INR4D1BWP16P90 g1041__6417(.A1 (n_11), .B1 (accum_uut_sum[4]), .B2
       (cWord[0]), .B3 (cWord[3]), .ZN (n_12));
  DFCNQD2BWP16P90 divide_uut_half_freq_reg(.CDN (RSTN), .CP (dco_out),
       .D (n_9), .Q (divide_uut_half_freq));
  DFCNQD2BWP16P90 pfd_uut_Q_DOWN_reg(.CDN (n_10), .CP (out_clk), .D
       (n_4), .Q (down_out));
  DFCNQD2BWP16P90 pfd_uut_Q_UP_reg(.CDN (n_10), .CP (CLK), .D (n_3), .Q
       (up_out));
  INR3D1BWP16P90 g1045__5477(.A1 (n_6), .B1 (cWord[1]), .B2 (cWord[4]),
       .ZN (n_11));
  DFCNQD2BWP16P90 divide_uut_quarter_freq_reg(.CDN (RSTN), .CP
       (divide_uut_half_freq), .D (n_8), .Q (divide_uut_quarter_freq));
  DFCNQD2BWP16P90 divide_uut_eighth_freq_reg(.CDN (RSTN), .CP
       (divide_uut_quarter_freq), .D (n_7), .Q (out_clk));
  XOR2D1BWP16P90 g1049__2398(.A1 (EN), .A2 (divide_uut_half_freq), .Z
       (n_9));
  AOI21D1BWP16P90 g1050__5107(.A1 (up_out), .A2 (down_out), .B (n_2),
       .ZN (n_10));
  XOR2D1BWP16P90 g1051__6260(.A1 (EN), .A2 (divide_uut_quarter_freq),
       .Z (n_8));
  XOR2D1BWP16P90 g1052__4319(.A1 (EN), .A2 (out_clk), .Z (n_7));
  NR2D1BWP16P90 g1053__8428(.A1 (accum_uut_sum[0]), .A2
       (accum_uut_sum[1]), .ZN (n_6));
  ND2D1BWP16P90 g1054__5526(.A1 (accum_uut_sum[0]), .A2
       (accum_uut_sum[1]), .ZN (n_5));
  OR2D1BWP16P90 g1055__6783(.A1 (EN), .A2 (down_out), .Z (n_4));
  OR2D1BWP16P90 g1056__3680(.A1 (EN), .A2 (up_out), .Z (n_3));
  CKND1BWP16P90 g1058(.I (RSTN), .ZN (n_2));
  IOAI21D1BWP16P90 g2__1617(.A1 (n_6), .A2 (n_15), .B (n_5), .ZN (n_1));
  IINR3D1BWP16P90 g1059__2802(.A1 (cWord[4]), .A2 (cWord[1]), .B1
       (n_5), .ZN (n_0));
endmodule

