###############################################################
#  Generated by:      Cadence Innovus 23.30-p003_1
#  OS:                Linux x86_64(Host ID dell52)
#  Generated on:      Mon May  4 13:59:25 2026
#  Design:            top
#  Command:           create_ccopt_clock_tree_spec -file ../data/top-ccopt_cts.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin CLK true

# Clocks present at pin CLK
#   CLK (period 1.000ns) in timing_config ss0p72vm40c_mode([/h/qvu01/EE166/1finalProject_placeandroute/Lab3_accel/work/top.place_opt.enc.dat/mmmc/modes/ss0p72vm40c_mode/ss0p72vm40c_mode.sdc])
#   CLK (period 1.000ns) in timing_config ff0p88v125c_mode([/h/qvu01/EE166/1finalProject_placeandroute/Lab3_accel/work/top.place_opt.enc.dat/mmmc/modes/ff0p88v125c_mode/ff0p88v125c_mode.sdc])
create_ccopt_clock_tree -name CLK -source CLK -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner ss_0p72v_m40c_delay_corner -early -clock_tree CLK 0.002
set_ccopt_property target_max_trans_sdc -delay_corner ss_0p72v_m40c_delay_corner -late -clock_tree CLK 0.005
# Clock period setting for source pin of CLK
set_ccopt_property clock_period -pin CLK 1

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_ccopt_property timing_connectivity_info {}

# Skew group to balance non generated clock:CLK in timing_config:ss0p72vm40c_mode (sdc /h/qvu01/EE166/1finalProject_placeandroute/Lab3_accel/work/top.place_opt.enc.dat/mmmc/modes/ss0p72vm40c_mode/ss0p72vm40c_mode.sdc)
create_ccopt_skew_group -name CLK/ss0p72vm40c_mode -sources CLK -auto_sinks
set_ccopt_property include_source_latency -skew_group CLK/ss0p72vm40c_mode true
set_ccopt_property extracted_from_clock_name -skew_group CLK/ss0p72vm40c_mode CLK
set_ccopt_property extracted_from_constraint_mode_names -skew_group CLK/ss0p72vm40c_mode {ss0p72vm40c_mode  }
set_ccopt_property extracted_from_delay_corners -skew_group CLK/ss0p72vm40c_mode ss_0p72v_m40c_delay_corner

# Skew group to balance non generated clock:CLK in timing_config:ff0p88v125c_mode (sdc /h/qvu01/EE166/1finalProject_placeandroute/Lab3_accel/work/top.place_opt.enc.dat/mmmc/modes/ff0p88v125c_mode/ff0p88v125c_mode.sdc)
create_ccopt_skew_group -name CLK/ff0p88v125c_mode -sources CLK -auto_sinks
set_ccopt_property include_source_latency -skew_group CLK/ff0p88v125c_mode true
set_ccopt_property extracted_from_clock_name -skew_group CLK/ff0p88v125c_mode CLK
set_ccopt_property extracted_from_constraint_mode_names -skew_group CLK/ff0p88v125c_mode {ff0p88v125c_mode  }
set_ccopt_property extracted_from_delay_corners -skew_group CLK/ff0p88v125c_mode ff_0p88v_125c_delay_corner


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

