/*
###############################################################
#  Generated by:      Cadence Innovus 23.30-p003_1
#  OS:                Linux x86_64(Host ID dell52)
#  Generated on:      Mon May  4 14:32:32 2026
#  Design:            top
#  Command:           saveNetlist ../data/top.pg.flat.v -flat -excludeLeafCell -includePowerGround -includePhysicalCell {DCAP8BWP20P90LVT DCAP8BWP20P90 DCAP8BWP16P90LVT DCAP8BWP16P90 DCAP64BWP20P90LVT DCAP64BWP20P90 DCAP64BWP16P90LVT DCAP64BWP16P90 DCAP4BWP20P90LVT DCAP4BWP20P90 DCAP4BWP16P90LVT DCAP4BWP16P90 DCAP32BWP20P90LVT DCAP32BWP20P90 DCAP32BWP16P90LVT DCAP32BWP16P90 DCAP16BWP20P90LVT DCAP16BWP20P90 DCAP16BWP16P90LVT DCAP16BWP16P90} -excludeCellInst {FILL8BWP20P90LVT FILL8BWP20P90 FILL8BWP16P90LVT FILL8BWP16P90 FILL64BWP20P90LVT FILL64BWP20P90 FILL64BWP16P90LVT FILL64BWP16P90 FILL4BWP20P90LVT FILL4BWP20P90 FILL4BWP16P90LVT FILL4BWP16P90 FILL3BWP20P90LVT FILL3BWP20P90 FILL3BWP16P90LVT FILL3BWP16P90 FILL32BWP20P90LVT FILL32BWP20P90 FILL32BWP16P90LVT FILL32BWP16P90 FILL2BWP20P90LVT FILL2BWP20P90 FILL2BWP16P90LVT FILL2BWP16P90 FILL1BWP20P90LVT FILL1BWP20P90 FILL1BWP16P90LVT FILL1BWP16P90 FILL16BWP20P90LVT FILL16BWP20P90 FILL16BWP16P90LVT FILL16BWP16P90}
###############################################################
*/
module top (
	CLK, 
	EN, 
	RSTN, 
	out_clk, 
	VSS, 
	VDD);
   input CLK;
   input EN;
   input RSTN;
   output out_clk;
   inout VSS;
   inout VDD;

   // Internal wires
   wire FE_PHN17_RSTN;
   wire FE_PHN16_n_0;
   wire FE_PHN15_n_0;
   wire FE_PHN14_RSTN;
   wire FE_PHN13_n_12;
   wire FE_PHN12_n_0;
   wire FE_PHN11_n_12;
   wire FE_PHN10_n_6;
   wire FE_PHN9_n_12;
   wire FE_PHN8_n_6;
   wire FE_PHN7_n_6;
   wire FE_PHN6_n_12;
   wire FE_PHN5_n_6;
   wire FE_PHN4_n_12;
   wire FE_PHN3_n_6;
   wire FE_PHN2_n_12;
   wire [4:0] cWord;
   wire [6:0] accum_uut_sum;
   wire dco_out;
   wire divide_uut_half_freq;
   wire divide_uut_quarter_freq;
   wire down_out;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire nand1_out;
   wire nand2_out;
   wire nand3_out;
   wire up_out;

   // Module instantiations
   BUFFD2BWP20P90 FE_PHC17_RSTN (
	.I(RSTN),
	.Z(FE_PHN17_RSTN), 
	.VSS(VSS), 
	.VPP(VDD), 
	.VDD(VDD), 
	.VBB(VSS));
   BUFFD2BWP20P90 FE_PHC16_n_0 (
	.I(FE_PHN15_n_0),
	.Z(FE_PHN16_n_0), 
	.VSS(VSS), 
	.VPP(VDD), 
	.VDD(VDD), 
	.VBB(VSS));
   BUFFD2BWP20P90 FE_PHC15_n_0 (
	.I(FE_PHN12_n_0),
	.Z(FE_PHN15_n_0), 
	.VSS(VSS), 
	.VPP(VDD), 
	.VDD(VDD), 
	.VBB(VSS));
   BUFFD2BWP20P90 FE_PHC14_RSTN (
	.I(FE_PHN17_RSTN),
	.Z(FE_PHN14_RSTN), 
	.VSS(VSS), 
	.VPP(VDD), 
	.VDD(VDD), 
	.VBB(VSS));
   BUFFD2BWP20P90 FE_PHC13_n_12 (
	.I(FE_PHN13_n_12),
	.Z(FE_PHN11_n_12), 
	.VSS(VSS), 
	.VPP(VDD), 
	.VDD(VDD), 
	.VBB(VSS));
   BUFFD2BWP20P90 FE_PHC12_n_0 (
	.I(n_0),
	.Z(FE_PHN12_n_0), 
	.VSS(VSS), 
	.VPP(VDD), 
	.VDD(VDD), 
	.VBB(VSS));
   BUFFD2BWP20P90 FE_PHC11_n_12 (
	.I(FE_PHN11_n_12),
	.Z(FE_PHN9_n_12), 
	.VSS(VSS), 
	.VPP(VDD), 
	.VDD(VDD), 
	.VBB(VSS));
   BUFFD2BWP20P90 FE_PHC10_n_6 (
	.I(FE_PHN10_n_6),
	.Z(FE_PHN8_n_6), 
	.VSS(VSS), 
	.VPP(VDD), 
	.VDD(VDD), 
	.VBB(VSS));
   BUFFD2BWP20P90 FE_PHC9_n_12 (
	.I(FE_PHN6_n_12),
	.Z(FE_PHN13_n_12), 
	.VSS(VSS), 
	.VPP(VDD), 
	.VDD(VDD), 
	.VBB(VSS));
   BUFFD2BWP20P90 FE_PHC8_n_6 (
	.I(FE_PHN8_n_6),
	.Z(FE_PHN7_n_6), 
	.VSS(VSS), 
	.VPP(VDD), 
	.VDD(VDD), 
	.VBB(VSS));
   BUFFD2BWP20P90 FE_PHC7_n_6 (
	.I(FE_PHN7_n_6),
	.Z(FE_PHN3_n_6), 
	.VSS(VSS), 
	.VPP(VDD), 
	.VDD(VDD), 
	.VBB(VSS));
   BUFFD2BWP20P90 FE_PHC6_n_12 (
	.I(FE_PHN2_n_12),
	.Z(FE_PHN6_n_12), 
	.VSS(VSS), 
	.VPP(VDD), 
	.VDD(VDD), 
	.VBB(VSS));
   BUFFD2BWP20P90 FE_PHC5_n_6 (
	.I(FE_PHN5_n_6),
	.Z(FE_PHN10_n_6), 
	.VSS(VSS), 
	.VPP(VDD), 
	.VDD(VDD), 
	.VBB(VSS));
   BUFFD2BWP20P90 FE_PHC4_n_12 (
	.I(FE_PHN9_n_12),
	.Z(FE_PHN4_n_12), 
	.VSS(VSS), 
	.VPP(VDD), 
	.VDD(VDD), 
	.VBB(VSS));
   BUFFD2BWP20P90 FE_PHC3_n_6 (
	.I(FE_PHN3_n_6),
	.Z(n_6), 
	.VSS(VSS), 
	.VPP(VDD), 
	.VDD(VDD), 
	.VBB(VSS));
   BUFFD2BWP20P90 FE_PHC2_n_12 (
	.I(n_12),
	.Z(FE_PHN2_n_12), 
	.VSS(VSS), 
	.VPP(VDD), 
	.VDD(VDD), 
	.VBB(VSS));
   DFCNQD1BWP20P90 pfd_uut_Q_UP_reg (
	.CDN(FE_PHN4_n_12),
	.CP(CLK),
	.D(n_6),
	.Q(up_out), 
	.VSS(VSS), 
	.VPP(VDD), 
	.VDD(VDD), 
	.VBB(VSS));
   DFCNQD1BWP20P90 divide_uut_eighth_freq_reg (
	.CDN(FE_PHN14_RSTN),
	.CP(divide_uut_quarter_freq),
	.D(n_9),
	.Q(out_clk), 
	.VSS(VSS), 
	.VPP(VDD), 
	.VDD(VDD), 
	.VBB(VSS));
   DFCNQD1BWP20P90 pfd_uut_Q_DOWN_reg (
	.CDN(n_12),
	.CP(out_clk),
	.D(n_4),
	.Q(down_out), 
	.VSS(VSS), 
	.VPP(VDD), 
	.VDD(VDD), 
	.VBB(VSS));
   DFCNQD1BWP20P90 divide_uut_half_freq_reg (
	.CDN(FE_PHN14_RSTN),
	.CP(dco_out),
	.D(n_10),
	.Q(divide_uut_half_freq), 
	.VSS(VSS), 
	.VPP(VDD), 
	.VDD(VDD), 
	.VBB(VSS));
   DFCNQD1BWP20P90 divide_uut_quarter_freq_reg (
	.CDN(FE_PHN14_RSTN),
	.CP(divide_uut_half_freq),
	.D(n_8),
	.Q(divide_uut_quarter_freq), 
	.VSS(VSS), 
	.VPP(VDD), 
	.VDD(VDD), 
	.VBB(VSS));
   AOI21D1BWP20P90 g1389__7098 (
	.A1(up_out),
	.A2(down_out),
	.B(n_1),
	.ZN(n_12), 
	.VSS(VSS), 
	.VPP(VDD), 
	.VDD(VDD), 
	.VBB(VSS));
   XNR2D1BWP20P90 g1390__6131 (
	.A1(n_0),
	.A2(divide_uut_half_freq),
	.ZN(n_10), 
	.VSS(VSS), 
	.VPP(VDD), 
	.VDD(VDD), 
	.VBB(VSS));
   XNR2D1BWP20P90 g1391__1881 (
	.A1(n_0),
	.A2(out_clk),
	.ZN(n_9), 
	.VSS(VSS), 
	.VPP(VDD), 
	.VDD(VDD), 
	.VBB(VSS));
   XNR2D1BWP20P90 g1392__5115 (
	.A1(n_0),
	.A2(divide_uut_quarter_freq),
	.ZN(n_8), 
	.VSS(VSS), 
	.VPP(VDD), 
	.VDD(VDD), 
	.VBB(VSS));
   IND2D1BWP20P90 g1393__7482 (
	.A1(up_out),
	.B1(FE_PHN16_n_0),
	.ZN(FE_PHN5_n_6), 
	.VSS(VSS), 
	.VPP(VDD), 
	.VDD(VDD), 
	.VBB(VSS));
   OR2D1BWP20P90 g1395__6161 (
	.A1(EN),
	.A2(down_out),
	.Z(n_4), 
	.VSS(VSS), 
	.VPP(VDD), 
	.VDD(VDD), 
	.VBB(VSS));
   CKND1BWP20P90 g1399 (
	.I(FE_PHN14_RSTN),
	.ZN(n_1), 
	.VSS(VSS), 
	.VPP(VDD), 
	.VDD(VDD), 
	.VBB(VSS));
   CKND1BWP20P90 g1400 (
	.I(EN),
	.ZN(n_0), 
	.VSS(VSS), 
	.VPP(VDD), 
	.VDD(VDD), 
	.VBB(VSS));
endmodule

