
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: May  4 2026 13:13:50 EDT (May  4 2026 17:13:50 UTC)

// Verification Directory fv/top 

module ro_netlist(EN, CTRL, NAND_CTRL1, NAND_CTRL2, NAND_CTRL3, CLK);
  input EN, NAND_CTRL1, NAND_CTRL2, NAND_CTRL3;
  input [4:0] CTRL;
  output CLK;
  wire EN, NAND_CTRL1, NAND_CTRL2, NAND_CTRL3;
  wire [4:0] CTRL;
  wire CLK;
endmodule

module top(CLK, EN, RSTN, out_clk);
  input CLK, EN, RSTN;
  output out_clk;
  wire CLK, EN, RSTN;
  wire out_clk;
  wire [4:0] cWord;
  wire [6:0] accum_uut_sum;
  wire dco_out, divide_uut_half_freq, divide_uut_quarter_freq,
       down_out, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, nand1_out, nand2_out, nand3_out, up_out;
  ro_netlist dco_uut(.EN (EN), .CTRL (cWord), .NAND_CTRL1 (nand1_out),
       .NAND_CTRL2 (nand2_out), .NAND_CTRL3 (nand3_out), .CLK
       (dco_out));
  DFCNQD2BWP16P90 \accum_uut_sum_reg[6] (.CDN (RSTN), .CP (dco_out), .D
       (n_53), .Q (cWord[4]));
  CKMUX2D1BWP16P90 g1333__2398(.I0 (cWord[4]), .I1 (n_51), .S (n_30),
       .Z (n_53));
  DFCNQD2BWP16P90 \accum_uut_sum_reg[5] (.CDN (RSTN), .CP (dco_out), .D
       (n_52), .Q (cWord[3]));
  CKMUX2D1BWP16P90 g1335__5107(.I0 (cWord[3]), .I1 (n_48), .S (n_30),
       .Z (n_52));
  XOR3D2BWP16P90 g1336__6260(.A1 (cWord[4]), .A2 (n_20), .A3 (n_50), .Z
       (n_51));
  DFCNQD2BWP16P90 \accum_uut_sum_reg[4] (.CDN (RSTN), .CP (dco_out), .D
       (n_49), .Q (cWord[2]));
  OAI211D1BWP16P90 g1338__4319(.A1 (n_22), .A2 (n_44), .B (n_21), .C
       (n_27), .ZN (n_50));
  CKMUX2D1BWP16P90 g1339__8428(.I0 (cWord[2]), .I1 (n_45), .S (n_30),
       .Z (n_49));
  XOR2D1BWP16P90 g1340__5526(.A1 (n_47), .A2 (n_29), .Z (n_48));
  DFCNQD2BWP16P90 \accum_uut_sum_reg[3] (.CDN (RSTN), .CP (dco_out), .D
       (n_46), .Q (cWord[1]));
  ND2D1BWP16P90 g1342__6783(.A1 (n_44), .A2 (n_21), .ZN (n_47));
  CKMUX2D1BWP16P90 g1343__3680(.I0 (cWord[1]), .I1 (n_40), .S (n_30),
       .Z (n_46));
  XOR2D1BWP16P90 g1344__1617(.A1 (n_43), .A2 (n_32), .Z (n_45));
  DFCNQD2BWP16P90 \accum_uut_sum_reg[2] (.CDN (RSTN), .CP (dco_out), .D
       (n_41), .Q (cWord[0]));
  IND2D1BWP16P90 g1346__2802(.A1 (n_24), .B1 (n_43), .ZN (n_44));
  DFCNQD2BWP16P90 \accum_uut_sum_reg[1] (.CDN (RSTN), .CP (dco_out), .D
       (n_42), .Q (accum_uut_sum[1]));
  CKMUX2D1BWP16P90 g1348__1705(.I0 (accum_uut_sum[1]), .I1 (n_36), .S
       (n_30), .Z (n_42));
  OAI211D1BWP16P90 g1349__5122(.A1 (n_26), .A2 (n_35), .B (n_25), .C
       (n_23), .ZN (n_43));
  CKMUX2D1BWP16P90 g1350__8246(.I0 (cWord[0]), .I1 (n_39), .S (n_30),
       .Z (n_41));
  XOR2D1BWP16P90 g1351__7098(.A1 (n_38), .A2 (n_33), .Z (n_40));
  DFCNQD2BWP16P90 \accum_uut_sum_reg[0] (.CDN (RSTN), .CP (dco_out), .D
       (n_37), .Q (accum_uut_sum[0]));
  XNR2D1BWP16P90 g1353__6131(.A1 (n_34), .A2 (n_31), .ZN (n_39));
  ND2D1BWP16P90 g1354__1881(.A1 (n_35), .A2 (n_25), .ZN (n_38));
  XOR2D1BWP16P90 g1355__5115(.A1 (n_30), .A2 (accum_uut_sum[0]), .Z
       (n_37));
  XOR3D2BWP16P90 g1356__7482(.A1 (accum_uut_sum[1]), .A2
       (accum_uut_sum[0]), .A3 (n_20), .Z (n_36));
  IND2D1BWP16P90 g1357__4733(.A1 (n_28), .B1 (n_31), .ZN (n_35));
  IND2D1BWP16P90 g1358__6161(.A1 (n_28), .B1 (n_25), .ZN (n_34));
  INR2D1BWP16P90 g1359__9315(.A1 (n_23), .B1 (n_26), .ZN (n_33));
  INR2D1BWP16P90 g1360__9945(.A1 (n_21), .B1 (n_24), .ZN (n_32));
  INR2D1BWP16P90 g1361__2883(.A1 (n_27), .B1 (n_22), .ZN (n_29));
  OAI21D1BWP16P90 g1362__2346(.A1 (n_19), .A2 (n_5), .B (n_7), .ZN
       (n_31));
  OAOI211D1BWP16P90 g1363__1666(.A1 (up_out), .A2 (n_18), .B (n_19), .C
       (n_0), .ZN (n_30));
  NR2D1BWP16P90 g1364__7410(.A1 (n_20), .A2 (cWord[0]), .ZN (n_28));
  ND2D1BWP16P90 g1365__6417(.A1 (n_20), .A2 (cWord[3]), .ZN (n_27));
  NR2D1BWP16P90 g1366__5477(.A1 (n_20), .A2 (cWord[1]), .ZN (n_26));
  ND2D1BWP16P90 g1367__2398(.A1 (n_20), .A2 (cWord[0]), .ZN (n_25));
  NR2D1BWP16P90 g1368__5107(.A1 (n_20), .A2 (cWord[2]), .ZN (n_24));
  ND2D1BWP16P90 g1369__6260(.A1 (n_20), .A2 (cWord[1]), .ZN (n_23));
  NR2D1BWP16P90 g1370__4319(.A1 (n_20), .A2 (cWord[3]), .ZN (n_22));
  ND2D1BWP16P90 g1371__8428(.A1 (n_20), .A2 (cWord[2]), .ZN (n_21));
  CKND1BWP16P90 g1372(.I (n_20), .ZN (n_19));
  INR3D1BWP16P90 g1373__5526(.A1 (up_out), .B1 (down_out), .B2 (n_17),
       .ZN (n_20));
  OAI31D1BWP16P90 g1374__6783(.A1 (n_2), .A2 (n_3), .A3 (n_16), .B
       (down_out), .ZN (n_18));
  INR4D1BWP16P90 g1375__3680(.A1 (n_15), .B1 (cWord[2]), .B2
       (cWord[0]), .B3 (cWord[3]), .ZN (n_17));
  DFCNQD2BWP16P90 accum_uut_nand1_reg(.CDN (RSTN), .CP (dco_out), .D
       (n_13), .Q (nand1_out));
  IND4D1BWP16P90 g1377__1617(.A1 (n_7), .B1 (cWord[1]), .B2 (cWord[4]),
       .B3 (cWord[3]), .ZN (n_16));
  DFCNQD2BWP16P90 accum_uut_nand3_reg(.CDN (RSTN), .CP (dco_out), .D
       (n_14), .Q (nand3_out));
  DFCNQD2BWP16P90 accum_uut_nand2_reg(.CDN (RSTN), .CP (dco_out), .D
       (n_11), .Q (nand2_out));
  DFCNQD2BWP16P90 pfd_uut_Q_UP_reg(.CDN (n_12), .CP (CLK), .D (n_6), .Q
       (up_out));
  DFCNQD2BWP16P90 divide_uut_eighth_freq_reg(.CDN (RSTN), .CP
       (divide_uut_quarter_freq), .D (n_9), .Q (out_clk));
  DFCNQD2BWP16P90 pfd_uut_Q_DOWN_reg(.CDN (n_12), .CP (out_clk), .D
       (n_4), .Q (down_out));
  INR3D1BWP16P90 g1383__2802(.A1 (n_5), .B1 (cWord[1]), .B2 (cWord[4]),
       .ZN (n_15));
  MOAI22D1BWP16P90 g1384__1705(.A1 (n_0), .A2 (n_7), .B1 (n_0), .B2
       (nand3_out), .ZN (n_14));
  MOAI22D1BWP16P90 g1385__5122(.A1 (n_0), .A2 (n_5), .B1 (n_0), .B2
       (nand1_out), .ZN (n_13));
  DFCNQD2BWP16P90 divide_uut_half_freq_reg(.CDN (RSTN), .CP (dco_out),
       .D (n_10), .Q (divide_uut_half_freq));
  DFCNQD2BWP16P90 divide_uut_quarter_freq_reg(.CDN (RSTN), .CP
       (divide_uut_half_freq), .D (n_8), .Q (divide_uut_quarter_freq));
  CKMUX2D1BWP16P90 g1388__8246(.I0 (accum_uut_sum[1]), .I1 (nand2_out),
       .S (n_0), .Z (n_11));
  AOI21D1BWP16P90 g1389__7098(.A1 (up_out), .A2 (down_out), .B (n_1),
       .ZN (n_12));
  XNR2D1BWP16P90 g1390__6131(.A1 (n_0), .A2 (divide_uut_half_freq), .ZN
       (n_10));
  XNR2D1BWP16P90 g1391__1881(.A1 (n_0), .A2 (out_clk), .ZN (n_9));
  XNR2D1BWP16P90 g1392__5115(.A1 (n_0), .A2 (divide_uut_quarter_freq),
       .ZN (n_8));
  IND2D1BWP16P90 g1393__7482(.A1 (up_out), .B1 (n_0), .ZN (n_6));
  ND2D1BWP16P90 g1394__4733(.A1 (accum_uut_sum[1]), .A2
       (accum_uut_sum[0]), .ZN (n_7));
  OR2D1BWP16P90 g1395__6161(.A1 (EN), .A2 (down_out), .Z (n_4));
  NR2D1BWP16P90 g1396__9315(.A1 (accum_uut_sum[1]), .A2
       (accum_uut_sum[0]), .ZN (n_5));
  CKND1BWP16P90 g1397(.I (cWord[2]), .ZN (n_3));
  CKND1BWP16P90 g1398(.I (cWord[0]), .ZN (n_2));
  CKND1BWP16P90 g1399(.I (RSTN), .ZN (n_1));
  CKND1BWP16P90 g1400(.I (EN), .ZN (n_0));
endmodule

