
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: May  4 2026 13:13:45 EDT (May  4 2026 17:13:45 UTC)

// Verification Directory fv/top 

module ro_netlist(EN, CTRL, NAND_CTRL1, NAND_CTRL2, NAND_CTRL3, CLK);
  input EN, NAND_CTRL1, NAND_CTRL2, NAND_CTRL3;
  input [4:0] CTRL;
  output CLK;
  wire EN, NAND_CTRL1, NAND_CTRL2, NAND_CTRL3;
  wire [4:0] CTRL;
  wire CLK;
endmodule

module top(CLK, EN, RSTN, out_clk);
  input CLK, EN, RSTN;
  output out_clk;
  wire CLK, EN, RSTN;
  wire out_clk;
  wire [6:0] accum_uut_sum;
  wire [4:0] cWord;
  wire dco_out, divide_uut_half_freq, divide_uut_quarter_freq,
       down_out, n_276, n_277, n_278, n_279;
  wire n_280, n_281, n_282, n_283, n_284, n_285, n_286, n_287;
  wire n_288, n_289, n_290, n_291, n_292, n_293, n_294, n_295;
  wire n_296, n_297, n_298, n_299, n_300, n_301, n_302, n_304;
  wire n_305, n_306, n_307, n_308, n_309, n_310, n_311, n_312;
  wire n_313, n_314, n_319, n_320, n_323, n_328, n_329, n_334;
  wire n_335, n_344, n_345, n_346, n_347, n_356, n_357, n_358;
  wire n_359, n_362, n_367, n_368, n_371, n_374, n_377, n_384;
  wire n_385, n_386, n_393, n_394, n_395, n_414, n_415, n_416;
  wire n_417, n_418, n_419, n_420, n_421, n_422, n_423, n_424;
  wire n_425, n_426, n_427, n_428, n_431, n_432, nand1_out, nand2_out;
  wire nand3_out, up_out;
  ro_netlist dco_uut(.EN (EN), .CTRL (cWord), .NAND_CTRL1 (nand1_out),
       .NAND_CTRL2 (nand2_out), .NAND_CTRL3 (nand3_out), .CLK
       (dco_out));
  not accum_uut_g641 (n_276, RSTN);
  not accum_uut_g643 (n_291, accum_uut_sum[0]);
  CDN_flop accum_uut_nand1_reg(.clk (dco_out), .d (n_302), .sena
       (1'b1), .aclr (n_276), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (nand1_out));
  CDN_flop accum_uut_nand2_reg(.clk (dco_out), .d (n_296), .sena
       (1'b1), .aclr (n_276), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (nand2_out));
  CDN_flop accum_uut_nand3_reg(.clk (dco_out), .d (n_297), .sena
       (1'b1), .aclr (n_276), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (nand3_out));
  CDN_flop \accum_uut_sum_reg[0] (.clk (dco_out), .d (n_291), .sena
       (n_424), .aclr (n_276), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (accum_uut_sum[0]));
  CDN_flop \accum_uut_sum_reg[1] (.clk (dco_out), .d (n_280), .sena
       (n_424), .aclr (n_276), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (accum_uut_sum[1]));
  CDN_flop \accum_uut_sum_reg[2] (.clk (dco_out), .d (n_301), .sena
       (n_424), .aclr (n_276), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (cWord[0]));
  CDN_flop \accum_uut_sum_reg[3] (.clk (dco_out), .d (n_305), .sena
       (n_424), .aclr (n_276), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (cWord[1]));
  CDN_flop \accum_uut_sum_reg[4] (.clk (dco_out), .d (n_299), .sena
       (n_424), .aclr (n_276), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (cWord[2]));
  CDN_flop \accum_uut_sum_reg[5] (.clk (dco_out), .d (n_307), .sena
       (n_424), .aclr (n_276), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (cWord[3]));
  CDN_flop \accum_uut_sum_reg[6] (.clk (dco_out), .d (n_290), .sena
       (n_424), .aclr (n_276), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (cWord[4]));
  CDN_flop divide_uut_eighth_freq_reg(.clk (divide_uut_quarter_freq),
       .d (n_294), .sena (EN), .aclr (n_276), .apre (1'b0), .srl
       (1'b0), .srd (1'b0), .q (out_clk));
  not divide_uut_g644 (n_292, divide_uut_half_freq);
  not divide_uut_g645 (n_293, divide_uut_quarter_freq);
  not divide_uut_g646 (n_294, out_clk);
  CDN_flop divide_uut_half_freq_reg(.clk (dco_out), .d (n_292), .sena
       (EN), .aclr (n_276), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (divide_uut_half_freq));
  CDN_flop divide_uut_quarter_freq_reg(.clk (divide_uut_half_freq), .d
       (n_293), .sena (EN), .aclr (n_276), .apre (1'b0), .srl (1'b0),
       .srd (1'b0), .q (divide_uut_quarter_freq));
  or g471 (n_277, accum_uut_sum[1], accum_uut_sum[0]);
  nand g658 (n_308, n_281, n_287);
  nand g661 (n_309, n_282, n_285);
  nand g752 (n_414, n_288, n_289);
  or g753 (n_415, n_288, n_289);
  nand g754 (n_290, n_414, n_415);
  or g755 (n_288, n_395, wc);
  not gc (wc, n_281);
  nand g756 (n_395, n_393, n_394);
  nand g757 (n_416, n_308, n_306);
  or g758 (n_417, n_308, n_306);
  nand g759 (n_307, n_416, n_417);
  or g760 (n_393, wc0, n_287);
  not gc0 (wc0, n_310);
  nand g761 (n_287, n_374, n_286);
  nand g762 (n_418, n_298, n_286);
  or g763 (n_419, n_298, n_286);
  nand g764 (n_299, n_418, n_419);
  or g765 (n_286, n_386, wc1);
  not gc1 (wc1, n_282);
  nand g766 (n_386, n_384, n_385);
  nand g767 (n_420, n_309, n_304);
  or g768 (n_421, n_309, n_304);
  nand g769 (n_305, n_420, n_421);
  or g770 (n_384, wc2, n_285);
  not gc2 (wc2, n_311);
  nand g771 (n_285, n_377, n_284);
  nand g772 (n_422, n_300, n_284);
  or g773 (n_423, n_300, n_284);
  nand g774 (n_301, n_422, n_423);
  nand g775 (n_300, n_282, n_377);
  nand g778 (n_298, n_281, n_374);
  nand g779 (n_284, n_283, n_371);
  nand g780 (n_425, accum_uut_sum[0], n_279);
  or g781 (n_426, accum_uut_sum[0], n_279);
  nand g782 (n_280, n_425, n_426);
  or g783 (n_310, cWord[3], wc3);
  not gc3 (wc3, n_278);
  or g784 (n_282, wc4, n_278);
  not gc4 (wc4, cWord[0]);
  or g785 (n_427, wc5, n_278);
  not gc5 (wc5, cWord[4]);
  or g786 (n_428, cWord[4], wc6);
  not gc6 (wc6, n_278);
  nand g787 (n_289, n_427, n_428);
  or g788 (n_371, n_278, wc7);
  not gc7 (wc7, n_277);
  or g789 (n_281, wc8, n_278);
  not gc8 (wc8, cWord[2]);
  nand g792 (n_306, n_394, n_310);
  or g793 (n_311, cWord[1], wc9);
  not gc9 (wc9, n_278);
  or g794 (n_385, wc10, n_278);
  not gc10 (wc10, cWord[1]);
  or g795 (n_394, wc11, n_278);
  not gc11 (wc11, cWord[3]);
  nand g796 (n_313, n_278, n_368);
  or g797 (n_374, cWord[2], wc12);
  not gc12 (wc12, n_278);
  or g798 (n_377, cWord[0], wc13);
  not gc13 (wc13, n_278);
  or g799 (n_431, wc14, n_278);
  not gc14 (wc14, accum_uut_sum[1]);
  or g800 (n_432, accum_uut_sum[1], wc15);
  not gc15 (wc15, n_278);
  nand g801 (n_279, n_431, n_432);
  nand g804 (n_304, n_385, n_311);
  or g805 (n_368, n_367, up_out);
  or g806 (n_278, n_362, wc16);
  not gc16 (wc16, up_out);
  or g807 (n_362, wc17, down_out);
  not gc17 (wc17, n_314);
  nand g808 (n_367, n_312, down_out);
  or g809 (n_312, n_347, wc18);
  not gc18 (wc18, cWord[3]);
  or g810 (n_314, n_359, cWord[3]);
  or g811 (n_359, n_358, cWord[2]);
  or g812 (n_347, n_346, wc19);
  not gc19 (wc19, cWord[2]);
  or g813 (n_346, n_345, wc20);
  not gc20 (wc20, cWord[1]);
  or g814 (n_358, n_357, cWord[1]);
  or g815 (n_345, n_344, wc21);
  not gc21 (wc21, cWord[0]);
  nand g816 (n_297, n_328, n_329);
  or g817 (n_357, n_356, cWord[0]);
  nand g818 (n_302, n_334, n_335);
  or g819 (n_329, n_283, wc22);
  not gc22 (wc22, EN);
  nand g820 (n_295, RSTN, n_323);
  nand g821 (n_296, n_319, n_320);
  nand g822 (n_335, n_277, EN);
  or g823 (n_344, n_283, wc23);
  not gc23 (wc23, cWord[4]);
  or g824 (n_356, n_277, cWord[4]);
  nand g825 (n_283, accum_uut_sum[1], accum_uut_sum[0]);
  or g826 (n_319, wc24, EN);
  not gc24 (wc24, nand2_out);
  nand g827 (n_320, accum_uut_sum[1], EN);
  nand g828 (n_323, down_out, up_out);
  or g829 (n_328, wc25, EN);
  not gc25 (wc25, nand3_out);
  or g830 (n_334, wc26, EN);
  not gc26 (wc26, nand1_out);
  and g831 (n_424, n_313, EN);
  CDN_flop pfd_uut_Q_DOWN_reg(.clk (out_clk), .d (1'b0), .sena (1'b0),
       .aclr (n_295), .apre (1'b0), .srl (EN), .srd (1'b1), .q
       (down_out));
  CDN_flop pfd_uut_Q_UP_reg(.clk (CLK), .d (1'b0), .sena (1'b0), .aclr
       (n_295), .apre (1'b0), .srl (EN), .srd (1'b1), .q (up_out));
endmodule

`ifdef RC_CDN_GENERIC_GATE
`else
module CDN_flop(clk, d, sena, aclr, apre, srl, srd, q);
  input clk, d, sena, aclr, apre, srl, srd;
  output q;
  wire clk, d, sena, aclr, apre, srl, srd;
  wire q;
  reg  qi;
  assign #1 q = qi;
  always 
    @(posedge clk or posedge apre or posedge aclr) 
      if (aclr) 
        qi <= 0;
      else if (apre) 
          qi <= 1;
        else if (srl) 
            qi <= srd;
          else begin
            if (sena) 
              qi <= d;
          end
  initial 
    qi <= 1'b0;
endmodule
`endif
